### ISSUE TITLE
May I ask some questions？

### ISSUE THREAD

**Issue by AliYa-chen** [bertt/mapbox_issues#1]
In your : https://bertt.github.io/mapbox_issues/draco/with_draco/    
I found that there is such a writing style

map.addSource('bag-3d', {
        "type": "batched-model",
        "maxzoom": 15,
        "minzoom": 15,
        "tiles": [
          "https://bertt.github.io/mapbox_issues/draco/with_draco/content/{z}-{x}-{y}.glb"
        ]
      }
)});

Among them {z}- {x}- {y}.glb，" {z}- {x}- {y} How was it obtained?
Is there a conversion tool available?

**Comment by bertt** [comment]
Hi, I've used pg2b3dm (https://github.com/Geodan/pg2b3dm) with --format mapbox option for testing. Sometimes it did work in Mapbox v3.

**Comment by AliYa-chen** [comment]
> Hi, I've used pg2b3dm (https://github.com/Geodan/pg2b3dm) with --format mapbox option for testing. Sometimes it did work in Mapbox v3.

Thank you very much for your help!
